development:
   adapter: mysql2
   database: api_rails 
   username: root
   password: phpmysql
   host: localhost
test:
   adapter: mysql2
   database: api_rails
   username: root
   password: phpmysql
   host: localhost
production:
   adapter: mysql2
   database: api_rails
   username: root
   password: phpmysql
   host: localhost